### ISSUE TITLE
Falta el www.example.org en los SKOS

### ISSUE THREAD

**Issue by ocorcho** [openuniversitydata/organizacion-y-servicios#9]
Por ejemplo, en esta línea y en las siguientes.

https://github.com/openuniversitydata/organizacion-y-servicios/blob/338a2e6c5ef0f5b3de05128ec8cddfa5f436e535/vocab-centros/examples/Centro%20Ejemplo.ttl#L16

**Comment by vcuende** [comment]
Pero al ser un SKOS no debería ir con la URI que ya lleva?

**Comment by ocorcho** [comment]
Lo mismo que se utilice para los conceptos y propiedades de la ontología, pero en este caso con /kos/ en lugar de /def/
